- hosts: service_host
  vars:
    source_conf_service_host: ../scripts/tmp-service-host/conf-files
    target_conf: ./
  tasks:
    - name: Removing files from earlier installation in service_host
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "./conf-files"
        - "./deploy-and-start-services.sh"
    - name: Copying conf-files to service_host
      copy:
        src: "{{ source_conf_service_host }}"
        dest: "{{ target_conf }}"
        mode: 0600
    - name: Copying service.conf to service_host
      copy:
        src: "{{ source_conf_service_host }}/service.conf"
        dest: "{{ target_conf }}/conf-files/service.conf"
        mode: 0644
    - name: Copying deploy-and-start-services.sh to service_host
      copy:
        src: "../scripts/tmp-service-host/deploy-and-start-services.sh"
        dest: "./deploy-and-start-services.sh"
        mode: 0700
    - name: Creating data directory
      file:
        path: ./data
        state: directory
        mode: 0700
    - name: Adding read permissions to required files
      file:
        path: ./conf-files/apache/index.html
        mode: 0644

- hosts: dmz_host
  vars:
    source_conf_dmz_host: ../scripts/tmp-dmz-host/conf-files
    target_conf: ./
  tasks:
    - name: Removing files from earlier installation in dmz_host
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "./conf-files"
        - "./deploy-and-start-services.sh"
    - name: Copying conf-files to dmz_host
      copy:
        src: "{{ source_conf_dmz_host }}"
        dest: "{{ target_conf }}"
        mode: 0600
    - name: Copying deploy-and-start-services.sh to dmz_host
      copy:
        src: "../scripts/tmp-dmz-host/deploy-and-start-services.sh"
        dest: "./deploy-and-start-services.sh"
        mode: 0700

- hosts: localhost
  connection: local
  tasks:
    - name: Removing conf-files from installation host
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "../scripts/tmp-service-host"
        - "../scripts/tmp-dmz-host"
