---
- hosts: basic-site-machine
  vars:
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    ras_dir_name: resource-allocation-service
    as_dir_name: authentication-service
    apache_server_dir_name: apache-server
  tasks:
    - name: Removing previously installed RAS, AS and Apache if applied
      become: yes
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ ras_dir_name }}"
        - "{{ fogbow_components }}/{{ as_dir_name }}"
        - "{{ fogbow_components }}/{{ apache_server_dir_name }}"