#!/bin/bash
/usr/sbin/a2enmod ssl_load
/usr/sbin/a2enmod proxy.load
/usr/sbin/a2enmod proxy_http.load

/usr/sbin/a2enmod ssl
/usr/sbin/a2enmod rewrite
/usr/sbin/a2enmod headers
/usr/sbin/a2enmod proxy_http

/usr/sbin/service apache2 restart
