#!/bin/bash
DIR=$(pwd)
CONF_FILES_DIR=$DIR/"conf-files"
SECRETS_FILE_PATH=$CONF_FILES_DIR/"secrets"
SHARED_INFO_FILE=$CONF_FILES_DIR/"shared.info"

VPN_PASSWORD_PROPERTY="vpn_password"
DB_PASSWORD_PROPERTY="db_password"

touch $SECRETS_FILE_PATH
chmod 600 $SECRETS_FILE_PATH

# Fill passwords
GENERATED_PASSWORD=$(pwgen 10 1)
echo "$DB_PASSWORD_PROPERTY=$GENERATED_PASSWORD" >> $SECRETS_FILE_PATH

GENERATED_PASSWORD=$(pwgen 10 1)
echo "$VPN_PASSWORD_PROPERTY=$GENERATED_PASSWORD" >> $SECRETS_FILE_PATH