#!/bin/bash
dir=$(pwd)
conf_files_dir=$dir/"conf-files"
aaa_plugins_dir=$conf_files_dir/"aaa-plugins"
gui_conf_dir="gui-confs"
gui_conf_file="gui.conf"
target_dir="services/resource-allocation-service/conf-files"

auth_type_pattern="authentication_type"
auth_type_class=$(grep $auth_type_pattern $conf_files_dir/$gui_conf_dir/$gui_conf_file | awk -F "=" '{print $2}')

openstack_class="openstack"
cloudstack_class="cloudstack"
opennebula_class="opennebula"
ldap_class="ldap"

if [ $auth_type_class = $openstack_class ]; then
	openstack_path=$aaa_plugins_dir/"local-user-credentials-mapper/keystone-v3-mapper.conf"
    yes | cp -f $openstack_path $target_dir
elif [ $auth_type_class = $cloudstack_class ]; then
	cloudstack_path=$aaa_plugins_dir/"local-user-credentials-mapper/cloudstack-mapper.conf"
    yes | cp -f $cloudstack_path $target_dir
elif [ $auth_type_class = $opennebula_class ]; then
	opennebula_path=$aaa_plugins_dir/"local-user-credentials-mapper/opennebula-mapper.conf"
    yes | cp -f $opennebula_path $target_dir
elif [ $auth_type_class = $ldap_class ]; then
	ldap_path=$aaa_plugins_dir/"token-generator/ldap-token-generator-plugin.conf"
    yes | cp -f $ldap_path $target_dir
fi
