---
- hosts: vanilla-agent-machine
  vars:
    fna_dir_name: federated-network-agent
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: bash fns-deploy-deploy-script.sh
  tasks:
    - name: Deploying services in vanilla-agent-machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ fna_dir_name }}"

- hosts: basic-site-machine
  vars:
    fns_dir_name: federated-network-service
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: bash fns-deploy-deploy-script.sh
  tasks:
    - name: Deploying services in basic-site-machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ fns_dir_name }}"