---
- hosts: vanilla-agent-machine
  vars:
    services_path: ../../services
    fna_dir_name: federated-network-agent
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying federated-network-agent to vanilla-agent-machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ fna_dir_name }}"

- hosts: basic-site-machine
  vars:
    services_path: ../../services
    fns_dir_name: federated-network-service
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying FNS service components
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ fns_dir_name }}"
