# This playbook transfers sensitive data, taking care of setting its permission in the remote machine accordingly

- hosts: basic-site-machine
  vars:
    fogbow_components: ~/fogbow-components
    conf_files: conf-files
    fns_dir_name: federated-network-service
    private_key_fns_to_dmz_path: ../../services/federated-network-service/conf-files/vanilla-agent-id_rsa
    private_key_fns_path: ../../services/federated-network-service/conf-files/id_rsa
    secrets_fns: ../../services/federated-network-service/conf-files/secrets
    fns_conf: ../../services/federated-network-service/conf-files/fns.conf
  tasks:
    - name: Copy private keys to basic-site-machine
      copy: src={{ item.src }} dest={{ item.dest }} mode=0600
      with_items:
        - { src: "{{ private_key_fns_to_dmz_path }}", dest: "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}" }
        - { src: "{{ private_key_fns_path }}", dest: "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}" }

    - name: Copy secrets file to internal machine
      copy: src={{ item.src }} dest={{ item.dest }} mode=0600
      with_items:
        - { src: "{{ secrets_fns }}", dest: "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}" }

    - name: Copy service specific configuration file to internal machine
      copy: src={{ item.src }} dest={{ item.dest }} mode=0600
      with_items:
        - { src: "{{ fns_conf }}", dest: "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}" }

- hosts: vanilla-agent-machine
  vars:
    fogbow_components: ~/fogbow-components
    agent_dir_name: federated-network-agent/conf-files
    ipsec_conf_path: ../../services/federated-network-agent/ipsec.conf
    fn_agent_dir_name: federated-network-agent
    secrets_agent: ../../services/federated-network-agent/conf-files/secrets
  tasks:
    - name: Copy secrets, prosody and ipsec confs to DMZ machine
      copy: src={{ item.src }} dest={{ item.dest }} mode=0600
      with_items:
        - { src: "{{ secrets_agent }}", dest: "{{ fogbow_components }}/{{ agent_dir_name }}" }
        - { src: '{{ ipsec_conf_path }}', dest: '{{ fogbow_components }}/{{ fn_agent_dir_name }}' }