#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${DB_NAME}"
echo "Creating database: ${DB2_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} to ${DB_USER};
CREATE DATABASE ${DB2_NAME} OWNER ${DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB2_NAME} to ${DB_USER};
EOSQL