#!/bin/bash
DIR_PATH=$(pwd)
EXTRA_FILES_DIR=$DIR_PATH/"extra-files"
CONF_FILES_DIR_PATH="conf-files"
CONF_FILES_DIR=$DIR_PATH/"conf-files"
FNS_CONF_FILES_PATH=$CONF_FILES_DIR/"ras-confs-to-fns"

CONTAINER_BASE_PATH="/root/federated-network-service"
CONTAINER_EXTRA_FILES_PATH=$CONTAINER_BASE_PATH/"extra-files"
CONTAINER_RESOURCES_PATH=$CONTAINER_BASE_PATH/src/main/resources
CONTAINER_CONF_FILES_DIR=$CONTAINER_RESOURCES_PATH/"private"

IMAGE_NAME="fogbow/federated-network-service"
CONTAINER_NAME="federated-network-service"

FEDNET_CONF_FILE_NAME="fns.conf"
LOG4F_FILE_NAME="log4j.properties"

APPLICATION_CONF_FILE="application.properties"

SERVER_PORT_PATTERN="server_port"
FEDNET_PORT=$(grep $SERVER_PORT_PATTERN $CONF_FILES_DIR_PATH/$FEDNET_CONF_FILE_NAME | awk -F "=" '{print $2}')
CONTAINER_PORT="8081"

IMAGE_BASE_NAME=$(basename $IMAGE_NAME)
SERVICES_CONF=services.conf
TAG=$(grep $IMAGE_BASE_NAME $CONF_FILES_DIR_PATH/$SERVICES_CONF | awk -F "=" '{print $2}')

echo "Federated network service server port: $FEDNET_PORT"

sudo docker stop $CONTAINER_NAME
sudo docker rm $CONTAINER_NAME
sudo docker pull $IMAGE_NAME

FEDNET_AGENT_SSH_PRIVATE_KEY_PATTERN="federated_network_agent_permission_file_path"
FEDNET_AGENT_SSH_PRIVATE_KEY=$(grep $FEDNET_AGENT_SSH_PRIVATE_KEY_PATTERN $FEDNET_CONF_FILE_NAME | awk -F "=" '{print $2}')
FEDNET_AGENT_SSH_PRIVATE_KEY=$(basename $FEDNET_AGENT_SSH_PRIVATE_KEY)
sudo chmod 600 $EXTRA_FILES_DIR/$FEDNET_AGENT_SSH_PRIVATE_KEY

sudo docker run -idt \
	--name $CONTAINER_NAME \
	-p $FEDNET_PORT:$CONTAINER_PORT \
	-v $CONF_FILES_DIR:$CONTAINER_CONF_FILES_DIR \
	-v $DIR_PATH/$APPLICATION_CONF_FILE:$CONTAINER_RESOURCES_PATH/$APPLICATION_CONF_FILE \
	-v $DIR_PATH/$LOG4F_FILE_NAME:$CONTAINER_BASE_PATH/$LOG4F_FILE_NAME \
	-v $EXTRA_FILES_DIR:$CONTAINER_EXTRA_FILES_PATH \
	$IMAGE_NAME:$TAG
