#!/bin/bash

CONF_FILE_TEMPLATE_PATH=../../conf-files
CONF_FILE_NAME=vlanid.conf
SERVICES_CONF_FILE_NAME=services.conf
SHARED_INFO_FILE_PATH=../shared.info
CONF_FILE_DIR_PATH=.

yes | cp -f $CONF_FILE_TEMPLATE_PATH/$CONF_FILE_NAME $CONF_FILE_DIR_PATH
yes | cp -f $CONF_FILE_TEMPLATE_PATH/$SERVICES_CONF_FILE_NAME $CONF_FILE_DIR_PATH
yes | cp -f $SHARED_INFO_FILE_PATH $CONF_FILE_DIR_PATH