---
- hosts: xmpp-machine
  vars:
    xmpp_dir_name: xmpp-server
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: bash federation-deploy-script.sh
  tasks:
    - name: Deploying services in XMPP machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ xmpp_dir_name }}"

- hosts: basic-site-machine
  vars:
    ms_dir_name: membership-service
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: bash federation-deploy-script.sh
  tasks:
    - name: Deploying services in basic-site-machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ ms_dir_name }}"