# This playbook transfers sensitive data, taking care of setting its permission in the remote machine accordingly

- hosts: xmpp-machine
  vars:
    fogbow_components: ~/fogbow-components
    prosody_conf_path: ../../services/xmpp-server/prosody.cfg.lua
    xmpp_dir_name: xmpp-server
  tasks:
    - name: Copy prosody to XMPP machine
      copy: src={{ item.src }} dest={{ item.dest }} mode=0600
      with_items:
        - { src: '{{ prosody_conf_path }}', dest: '{{ fogbow_components }}/{{ xmpp_dir_name }}' }
