---
- hosts: basic-site-machine
  vars:
    services_path: ../../services
    ras_dir_name: resource-allocation-service
    as_dir_name: authentication-service
    database_dir_name: fogbow-database
    apache_dir_name: apache-server
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying RAS and AS service components
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ ras_dir_name }}"
        - "{{ services_path }}/{{ as_dir_name }}"
        - "{{ services_path }}/{{ database_dir_name }}"
        - "{{ services_path }}/{{ apache_dir_name }}"
