- hosts: xmpp-machine
  vars:
    script_name: start-services-on-xmpp-machine-after-startup
    source_dir: ../../scripts
    target_dir: /etc/init.d
  tasks:
    - name: Copying scripts to XMPP machine
      become: yes
      copy: 
        src: "{{ source_dir }}/{{ script_name }}"
        dest: "{{ target_dir }}/{{ script_name }}"
        mode: 0755
    - name: Adding script as a service in XMPP machine
      become: yes
      command: update-rc.d "{{ script_name }}" defaults