#!/bin/bash
DIR=$(pwd)
CONF_FILES_DIR=$DIR/"../../conf-files"
SECRETS_FILE_PATH=$CONF_FILES_DIR/"secrets"
CERT_CONF_FILE_NAME="certificate-files.conf"

XMPP_PASSWORD_PROPERTY="xmpp_password"

touch $SECRETS_FILE_PATH
chmod 600 $SECRETS_FILE_PATH

# Fill passwords
GENERATED_PASSWORD=$(pwgen 10 1)
echo "$XMPP_PASSWORD_PROPERTY=$GENERATED_PASSWORD" >> $SECRETS_FILE_PATH

