#!/bin/bash
DIR=$(pwd)
CONF_FILES_DIR=$DIR/"../../conf-files"
SECRETS_FILE_PATH=$CONF_FILES_DIR/"secrets"
CERT_CONF_FILE_NAME="certificate-files.conf"

XMPP_PASSWORD_PROPERTY="xmpp_password"

touch $SECRETS_FILE_PATH
chmod 600 $SECRETS_FILE_PATH

# Fill passwords
GENERATED_PASSWORD=$(pwgen 10 1)
echo "$XMPP_PASSWORD_PROPERTY=$GENERATED_PASSWORD" >> $SECRETS_FILE_PATH

# Setup of new configuration files for services that need to be reconfigured

## Reconfiguring apache-server

CONF_FILES_DIR_NAME="conf-files"
BASE_DIR="services/apache-server"
HOST_CONF_NAME="hosts.conf"
APACHE_CONF_FILES_DIR_NAME="apache-confs"
CONF_FILES_DIR=$DIR/$CONF_FILES_DIR_NAME

### Copy shared file
SHARED_INFO="shared.info"
yes | cp -f $DIR/"services"/$CONF_FILES_DIR_NAME/$SHARED_INFO $BASE_DIR/$SHARED_INFO

### Moving apache certificate files
yes | cp -f $CONF_FILES_DIR/$APACHE_CONF_FILES_DIR_NAME/"certificate-files.conf" ./$BASE_DIR/"certificate-files.conf"

### Resolving certification files for https
CERTIFICATE_FILE="SSL_certificate_file_path"
CERTIFICATE_FILE_PATH=$(grep $CERTIFICATE_FILE $CONF_FILES_DIR/$APACHE_CONF_FILES_DIR_NAME/$CERT_CONF_FILE_NAME | awk -F "=" '{print $2}')
CERTIFICATE_FILE_NAME=$(basename $CERTIFICATE_FILE_PATH)

CERTIFICATE_KEY_FILE="SSL_certificate_key_file_path"
CERTIFICATE_KEY_FILE_PATH=$(grep $CERTIFICATE_KEY_FILE $CONF_FILES_DIR/$APACHE_CONF_FILES_DIR_NAME/$CERT_CONF_FILE_NAME | awk -F "=" '{print $2}')
CERTIFICATE_KEY_FILE_NAME=$(basename $CERTIFICATE_KEY_FILE_PATH)

CERTIFICATE_CHAIN_FILE="SSL_certificate_chain_file_path"
CERTIFICATE_CHAIN_FILE_PATH=$(grep $CERTIFICATE_CHAIN_FILE $CONF_FILES_DIR/$APACHE_CONF_FILES_DIR_NAME/$CERT_CONF_FILE_NAME | awk -F "=" '{print $2}')
CERTIFICATE_CHAIN_FILE_NAME=$(basename $CERTIFICATE_CHAIN_FILE_PATH)

### Fill certificate files in virtual host
VIRTUAL_HOST_FILE_TEMPLATE="000-federation.conf.template"
VIRTUAL_HOST_FILE="000-default.conf"
yes | cp -f $BASE_DIR/$VIRTUAL_HOST_FILE_TEMPLATE $BASE_DIR/$VIRTUAL_HOST_FILE
SSL_DIR="/etc/ssl/private"
CERTS_DIR="/etc/ssl/certs"

CERTIFICATE_PATTERN="SSLCertificateFile"
sed -i "s#$CERTIFICATE_PATTERN.*#$CERTIFICATE_PATTERN $CERTS_DIR/$CERTIFICATE_FILE_NAME#" $BASE_DIR/$VIRTUAL_HOST_FILE

CERTIFICATE_KEY_PATTERN="SSLCertificateKeyFile"
sed -i "s#$CERTIFICATE_KEY_PATTERN.*#$CERTIFICATE_KEY_PATTERN $SSL_DIR/$CERTIFICATE_KEY_FILE_NAME#" $BASE_DIR/$VIRTUAL_HOST_FILE

CERTIFICATE_CHAIN_PATTERN="SSLCertificateChainFile"
sed -i "s#$CERTIFICATE_CHAIN_PATTERN.*#$CERTIFICATE_CHAIN_PATTERN $CERTS_DIR/$CERTIFICATE_CHAIN_FILE_NAME#" $BASE_DIR/$VIRTUAL_HOST_FILE

### Fill redirects and proxy configurations in vhost file

#### replace basic_site_host_private_ip and basic_site_host_name
BASIC_SITE_HOST_IP_PATTERN="basic_site_host_ip"
BASIC_SITE_HOST_IP=$(grep $BASIC_SITE_HOST_IP_PATTERN $CONF_FILES_DIR/$HOST_CONF_NAME | awk -F "=" '{print $2}')
BASIC_SITE_HOST_NAME_PATTERN="basic_site_host_name"
BASIC_SITE_HOST_NAME=$(grep $BASIC_SITE_HOST_NAME_PATTERN $CONF_FILES_DIR/$HOST_CONF_NAME | awk -F "=" '{print $2}')

sed -i "s|$BASIC_SITE_HOST_IP_PATTERN|$BASIC_SITE_HOST_IP|g" $BASE_DIR/$VIRTUAL_HOST_FILE
sed -i "s|$BASIC_SITE_HOST_NAME_PATTERN|$BASIC_SITE_HOST_NAME|g" $BASE_DIR/$VIRTUAL_HOST_FILE

#### replace certificate files

CRT_FILE_PATTERN="crt_file"
sed -i "s|$CRT_FILE_PATTERN|$CERTIFICATE_FILE_NAME|g" $BASE_DIR/$VIRTUAL_HOST_FILE

KEY_FILE_PATTERN="key_file"
sed -i "s|$KEY_FILE_PATTERN|$CERTIFICATE_KEY_FILE_NAME|g" $BASE_DIR/$VIRTUAL_HOST_FILE

CHAIN_FILE_PATTERN="chain_file"
sed -i "s|$CHAIN_FILE_PATTERN|$CERTIFICATE_CHAIN_FILE_NAME|g" $BASE_DIR/$VIRTUAL_HOST_FILE

AS_PORT=$(grep ^as_port $BASE_DIR/$SHARED_INFO | awk -F "=" '{print $2}')
AS_PORT_PATTERN="as_port"

MS_PORT=$(grep ^ms_port $BASE_DIR/$SHARED_INFO | awk -F "=" '{print $2}')
MS_PORT_PATTERN="ms_port"

sed -i "s|$RAS_PORT_PATTERN|$RAS_PORT|g" $BASE_DIR/$VIRTUAL_HOST_FILE
sed -i "s|$AS_PORT_PATTERN|$AS_PORT|g" $BASE_DIR/$VIRTUAL_HOST_FILE
sed -i "s|$MS_PORT_PATTERN|$MS_PORT|g" $BASE_DIR/$VIRTUAL_HOST_FILE

### Update documentation file
DOCUMENTATION_TEMPLATE_FILE="federation-index.html"
DOCUMENTATION_FILE="index.html"

yes | cp -f $BASE_DIR/$DOCUMENTATION_TEMPLATE_FILE $BASE_DIR/$DOCUMENTATION_FILE

sed -i "s|$BASIC_SITE_HOST_IP_PATTERN|$BASIC_SITE_HOST_IP|g" $BASE_DIR/$DOCUMENTATION_FILE
sed -i "s|$BASIC_SITE_HOST_NAME_PATTERN|$BASIC_SITE_HOST_NAME|g" $BASE_DIR/$DOCUMENTATION_FILE
sed -i "s|$RAS_PORT_PATTERN|$RAS_PORT|g" $BASE_DIR/$DOCUMENTATION_FILE
sed -i "s|$AS_PORT_PATTERN|$AS_PORT|g" $BASE_DIR/$DOCUMENTATION_FILE
sed -i "s|$MS_PORT_PATTERN|$MS_PORT|g" $BASE_DIR/$DOCUMENTATION_FILE
