- hosts: service_host
  vars:
    source_conf: ../conf-files
    target_conf: ./
  tasks:
    - name: Copying conf-files to service_host
      become: yes
      copy:
        src: "{{ source_conf }}"
        dest: "{{ target_conf }}"
        mode: 0600
    - name: Copying service.conf to service_host
      become: yes
      copy:
        src: "{{ source_conf }}/service.conf"
        dest: "{{ target_conf }}/service.conf"
        mode: 0644
    - name: Copying deploy-and-start-services.sh to service_host
      become: yes
      copy:
        src: "../deploy-and-start-services.sh"
        dest: "./deploy-and-start-services.sh"
        mode: 0700
    - name: Creating data directory
      become: yes
      file:
        path: ./data
        state: directory
        mode: 0700
    - name: Removing templates directory in service_host
      become: yes
      file:
        path: ./conf-files/templates
        state: absent
    - name: Add read permissions to required files
      become: yes
      file:
        path: ./conf-files/apache/index.html
        mode: 0644
