- hosts: service_host
  vars:
    source_conf: ../conf-files
    target_conf: ./
  tasks:
    - name: Copying conf-files to service_host
      become: yes
      copy:
        src: "{{ source_conf }}/{{ item }}"
        dest: "{{ target_conf }}/{{ item }}"
        mode: 0600
      with_items:
          - "apache"
          - "as"
          - "gui"
          - "ras"
    - name: Copying service.conf to service_host
      become: yes
      copy:
        src: "{{ source_conf }}/service.conf"
        dest: "{{ target_conf }}/service.conf"
        mode: 0600
    - name: Copying deploy-and-start-services.sh to service_host
      become: yes
      copy:
        src: "../deploy-and-start-services.sh"
        dest: "./deploy-and-start-services.sh"
        mode: 0700
    - name: Creating data directory
      become: yes
      file:
        path: ./data
        state: directory
        mode: 0700
