- hosts: service_host
  vars:
    source_conf: ../conf-files
    target_conf: ./
    source_start: ../deploy-and-start-services.sh
    target_start: ./deploy-and-start-services.sh
  tasks:
    - name: Copying conf-files to service_host
      become: yes
      copy:
        src: "{{ source_conf }}"
        dest: "{{ target_conf }}"
        mode: 0600
    - name: Copying deploy-and-start-services.sh to service_host
      become: yes
      copy:
        src: "{{ source_start }}"
        dest: "{{ target_start }}"
        mode: 0700
    - name: Creating data directory
      become: yes
      file:
        path: /home/ubuntu/data
        state: directory
        mode: 0700
    - name: Removing templates
      file:
        path: /home/ubuntu/conf-files/templates
        state: absent
