---
- hosts: dmz-machine
  vars:
    xmpp_dir_name: xmpp-server
    fednet_agent_dir_name: federated-network-agent
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: sh deploy-script.sh
  tasks:
    - name: Deploying services in DMZ Machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ xmpp_dir_name }}"
        - "{{ fogbow_components }}/{{ fednet_agent_dir_name }}"

- hosts: internal-machine
  vars:
    manager_dir_name: resource-allocation-service
    membership_dir_name: membership-service
    dashboard_dir_name: fogbow-gui
    fednet_dir_name: federated-network-service
    database_dir_name: fogbow-database
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    deploy_script_runner: sh deploy-script.sh
  tasks:
    - name: Deploying services in Internal Machine
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ manager_dir_name }}"
        - "{{ fogbow_components }}/{{ membership_dir_name }}"
        - "{{ fogbow_components }}/{{ dashboard_dir_name }}"
        - "{{ fogbow_components }}/{{ fednet_dir_name }}"
        - "{{ fogbow_components }}/{{ database_dir_name }}"
