---
- hosts: dmz-machine:internal-machine
  tasks:
    - name: Installing Docker
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      become: yes
      with_items:
        - docker.io
