---
- hosts: dmz-machine
  vars:
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    xmpp_server: "xmpp-server"
    federated_network_agent: "federated-network-agent"
    general_conf: "general.conf" # We should get this property dinamically
  tasks:
    - name: Removing xmpp-server
      become: yes
      file:
        state: absent
        path: "{{ fogbow_components }}/{{ xmpp_server }}"
    - name: Removing general.conf from federated-network-agent
      become: yes
      file:
        state: absent
        path: "{{ fogbow_components }}/{{ federated_network_agent }}/{{ general_conf }}"

- hosts: internal-machine
  vars:
    fogbow_components: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-components"
    manager_dir_name: resource-allocation-service
    membership_dir_name: membership-service
    dashboard_dir_name: fogbow-gui
    fednet_dir_name: federated-network-service
  tasks:
    - name: Removing all services if applied
      become: yes
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ fogbow_components }}/{{ manager_dir_name }}"
        - "{{ fogbow_components }}/{{ membership_dir_name }}"
        - "{{ fogbow_components }}/{{ dashboard_dir_name }}"
        - "{{ fogbow_components }}/{{ fednet_dir_name }}"