# This playbook must to transfer sensitive datas, always taking care in its permission in remote machine
- hosts: internal-machine
  vars:
    general_conf_path: ../conf-files/general.conf
    fogbow_components: ~/fogbow-components
    fns_dir_name: federated-network-service
    conf_files: conf-files
    dmz_pk_pattern: dmz_private_key_file_path
  tasks:
    - name: Get DMZ private key path
      shell: grep "{{ dmz_pk_pattern }} {{ general_conf_path }}" | awk -F "=" '{print $2}'
      register: dmz_pk_path
    - name: Copying private key to access DMZ to Internal-Machine
      copy:
        src: "{{ dmz_pk_path }}"
        dest: "{{ item }}"
        mode: 0600
      with_items:
        - "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}"

- hosts: internal-machine
  vars:
    general_conf_path: ../conf-files/general.conf
    fogbow_components: ~/fogbow-components
    fns_dir_name: federated-network-service
    ras_dir_name: resource-allocation-service
    conf_files: conf-files
    pk_file_pattern: private_key_file_path
  tasks:
    - name: Get DMZ private key path
      shell: grep "{{ pk_file_pattern }} {{ general_conf_path }}" | awk -F "=" '{print $2}'
      register: dmz_pk_path
    - name: Copying private key to Internal-Machine
      copy:
        src: "{{ dmz_pk_path }}"
        dest: "{{ item }}"
        mode: 0600
      with_items:
        - "{{ fogbow_components }}/{{ fns_dir_name }}/{{ conf_files }}"
        - "{{ fogbow_components }}/{{ ras_dir_name }}/{{ conf_files }}"
