- hosts: internal-machine
  vars:
    script_name: start-services-on-internal-after-startup
    source_dir: ../scripts
    target_dir: /etc/init.d
  tasks:
    - name: Copy script to internal-machine
      become: yes
      copy: 
        src: "{{ source_dir }}/{{ script_name }}"
        dest: "{{ target_dir }}/{{ script_name }}"
        mode: 0755
    - name: Add script as a service in internal-machine
      become: yes
      command: update-rc.d "{{ script_name }}" defaults
  
- hosts: dmz-machine
  vars:
    script_name: start-services-on-dmz-after-startup
    source_dir: ../scripts
    target_dir: /etc/init.d
  tasks:
    - name: Copy script to dmz-machine
      become: yes
      copy: 
        src: "{{ source_dir }}/{{ script_name }}"
        dest: "{{ target_dir }}/{{ script_name }}"
        mode: 0755
    - name: Add script as a service in dmz-machine
      become: yes
      command: update-rc.d "{{ script_name }}" defaults
  