---
- hosts: dmz-machine
  vars:
    services_path: ../services
    xmpp_dir_name: xmpp-server
    fednet_agent_dir_name: federated-network-agent
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying services to DMZ-Machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ xmpp_dir_name }}"
        - "{{ services_path }}/{{ fednet_agent_dir_name }}"

- hosts: internal-machine
  vars:
    services_path: ../services
    manager_dir_name: resource-allocation-service
    membership_dir_name: membership-service
    dashboard_dir_name: fogbow-gui
    fednet_dir_name: federated-network-service
    database_dir_name: fogbow-database
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying services to Internal-Machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ manager_dir_name }}"
        - "{{ services_path }}/{{ membership_dir_name }}"
        - "{{ services_path }}/{{ dashboard_dir_name }}"
        - "{{ services_path }}/{{ fednet_dir_name }}"
        - "{{ services_path }}/{{ database_dir_name }}"

- hosts: internal-machine
  vars:
    services_path: ../services
    fednet_dir_name: federated-network-service
    fogbow_components: ~/fogbow-components
    conf_files: conf-files
    private_key_name: dmz-id_rsa # We should get this property dinamically
  tasks:
    - name: Copying private key to access DMZ to Internal-Machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}/{{ fednet_dir_name }}/{{ conf_files }}"
        mode: 0600
      with_items:
        - "{{ services_path }}/{{ fednet_dir_name }}/{{ conf_files }}/{{ private_key_name }}"
