---
- hosts: dmz-machine
  vars:
    services_path: ../services
    xmpp_dir_name: xmpp-server
    reverse_tunnel: reverse-tunnel-service
    fednet_agent_dir_name: federated-network-agent
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying services to DMZ-Machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ xmpp_dir_name }}"
        - "{{ services_path }}/{{ reverse_tunnel }}"
        - "{{ services_path }}/{{ fednet_agent_dir_name }}"

- hosts: internal-machine
  vars:
    services_path: ../services
    manager_dir_name: resource-allocation-service
    membership_dir_name: membership-service
    dashboard_dir_name: fogbow-gui
    fednet_dir_name: federated-network-service
    fogbow_components: ~/fogbow-components/
  tasks:
    - name: Copying services to Internal-Machine
      copy:
        src: "{{ item }}"
        dest: "{{ fogbow_components }}"
      with_items:
        - "{{ services_path }}/{{ manager_dir_name }}"
        - "{{ services_path }}/{{ membership_dir_name }}"
        - "{{ services_path }}/{{ dashboard_dir_name }}"
        - "{{ services_path }}/{{ fednet_dir_name }}"
