#!/bin/bash
DIR=$(pwd)
BASE_DIR="services/membership-service"
MS_CONF_NAME="ms.conf"
SHARED_INFO_FILE_NAME="shared.info"
SERVICES_FILE_NAME="services.conf"
CONF_FILES_DIR_NAME="conf-files"
CONF_FILES_DIR=$DIR/$CONF_FILES_DIR_NAME
SERVICE_CONF_FILES_DIR=$BASE_DIR/$CONF_FILES_DIR_NAME
CONF_FILE_PATH=$BASE_DIR/$CONF_FILES_DIR_NAME/$MS_CONF_NAME
SHARED_INFO_FILE=$DIR/"services"/$CONF_FILES_DIR_NAME/$SHARED_INFO_FILE_NAME

# Copy ms.conf
yes | cp -f $DIR/$CONF_FILES_DIR_NAME/$MS_CONF_NAME ./$SERVICE_CONF_FILES_DIR/$MS_CONF_NAME
# Copy services file
yes | cp -f $DIR/$CONF_FILES_DIR_NAME/$SERVICES_FILE_NAME ./$SERVICE_CONF_FILES_DIR/$SERVICES_FILE_NAME
# Copy shared file
yes | cp -f $DIR/"services"/$CONF_FILES_DIR_NAME/$SHARED_INFO_FILE_NAME ./$SERVICE_CONF_FILES_DIR/$SHARED_INFO_FILE_NAME
