#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <git ms_branch> <docker_tag>"
  exit 1
fi

dependecies_properties_path=../src/main/resources/dependencies.properties
common_pattern="common.git\="

ms_branch=$1
docker_tag=$2
common_branch=$(grep $common_pattern $dependecies_properties_path | awk '{split($0,a,"$common_pattern"); print a[2]}')

sudo docker build --build-arg MS_BRANCH=$ms_branch --build-arg \
 --build-arg COMMON_BRANCH=$common_branch --no-cache -t fogbow/membership-service:$docker_tag .

