#!/bin/bash
DIR_PATH=$(pwd)

IMAGE_NAME="fogbow/fogbow-gui"
CONTAINER_NAME="fogbow-gui"
CONF_FILE_NAME="api.config.js"

CONTAINER_BASE_PATH="/fogbow-gui"
CONTAINER_CONF_FILE_PATH="src/defaults"

MANAGER_CONF_FILE="ras.conf"
DASHBOARD_PORT_PATTERN="fogbow_gui_server_port"
DASHBOARD_PORT=$(grep $DASHBOARD_PORT_PATTERN $MANAGER_CONF_FILE | awk -F "=" '{print $2}')

IMAGE_BASE_NAME=$(basename $IMAGE_NAME)
SERVICES_CONF=services.conf
TAG=$(grep $IMAGE_BASE_NAME $SERVICES_CONF | awk -F "=" '{print $2}')

if [ -z "$DASHBOARD_PORT" ]; then
	DASHBOARD_PORT="80"
fi
echo "Dashboard port: $DASHBOARD_PORT"

# Certificate files
CERT_CONF_FILE="certificate-files.conf"

CERTIFICATE_FILE="SSL_certificate_file_path"
CERTIFICATE_FILE_PATH=$(grep $CERTIFICATE_FILE $CERT_CONF_FILE | awk -F "=" '{print $2}')
CERTIFICATE_FILE_NAME=$(basename $CERTIFICATE_FILE_PATH)

CERTIFICATE_KEY_FILE="SSL_certificate_key_file_path"
CERTIFICATE_KEY_FILE_PATH=$(grep $CERTIFICATE_KEY_FILE $CERT_CONF_FILE | awk -F "=" '{print $2}')
CERTIFICATE_KEY_FILE_NAME=$(basename $CERTIFICATE_KEY_FILE_PATH)

CERTIFICATE_CHAIN_FILE="SSL_certificate_chain_file_path"
CERTIFICATE_CHAIN_FILE_PATH=$(grep $CERTIFICATE_CHAIN_FILE $CERT_CONF_FILE | awk -F "=" '{print $2}')
CERTIFICATE_CHAIN_FILE_NAME=$(basename $CERTIFICATE_CHAIN_FILE_PATH)

SSL_DIR="/etc/ssl/private"
VIRTUAL_HOST_DIR="/etc/apache2/sites-enabled"
VIRTUAL_HOST_FILE="000-default.conf"

CONTAINER_PORT="3000"

sudo docker stop $CONTAINER_NAME
sudo docker rm $CONTAINER_NAME
sudo docker pull $IMAGE_NAME

sudo docker run -tdi --name $CONTAINER_NAME \
	-p $DASHBOARD_PORT:$CONTAINER_PORT \
	-v $CERTIFICATE_FILE_NAME:$SSL_DIR/$CERTIFICATE_FILE_NAME \
	-v $CERTIFICATE_KEY_FILE_NAME:$SSL_DIR/$CERTIFICATE_KEY_FILE_NAME \
	-v $CERTIFICATE_CHAIN_FILE_NAME:$SSL_DIR/$CERTIFICATE_CHAIN_FILE_NAME \
	-v $VIRTUAL_HOST_FILE:$VIRTUAL_HOST_DIR/$VIRTUAL_HOST_FILE \
	-v $DIR_PATH/$CONF_FILE_NAME:$CONTAINER_BASE_PATH/$CONTAINER_CONF_FILE_PATH/$CONF_FILE_NAME \
	$IMAGE_NAME:$TAG

