#!/bin/bash
### BEGIN INIT INFO
# Provides:          start-services-on-internal-after-startup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start fogbow services after machine startup
# Description:       Start all fogbow services in case of machine
#                    reboot, right after startup
### END INIT INFO

CONTAINERS_ID=$(docker ps -a | awk 'NR>1 {print $1}')
for id in $CONTAINERS_ID; do sudo docker start $id; done
