#!/bin/bash
### BEGIN INIT INFO
# Provides:          start-services-on-vanilla-agent-after-startup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start fogbow services after machine startup
# Description:       Start all fogbow services in case of machine
#                    reboot, right after startup
### END INIT INFO

ipsec restart # since strongswan isn't inside a container, we made (re)start hard coded
