version: '3'
services:
  apache:
    image: "fogbow/apache-shibboleth-server:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf-files/apache/site.crt:/etc/ssl/certs/site.crt
      - ./conf-files/apache/site.key:/etc/ssl/private/site.key
      - ./conf-files/apache/site.pem:/etc/ssl/certs/site.pem
      - ./conf-files/apache/ports.conf:/etc/apache2/ports.conf
      - ./conf-files/apache/000-default.conf:/etc/apache2/sites-availability/000-default.conf
      - ./conf-files/apache/index.html:/var/www/html/index.html
  database:
    image: "fogbow/database:latest"
    ports:
      - "5432:5432"
    environment:
      - DB_USER="fogbow"
      - DB_PASS="pass"
      - DB_NAME="ras"
      - DB2_NAME="fns"
    volumes:
      - ./data:/var/lib/postgresql/data
#  as:
#    build:
#      context: ./docker/as
#      args:
#        COMMON_BRANCH: develop
#        AS_BRANCH: develop
  as:
    image: fogbow/authentication-service:develop
    ports:
      - "8080:8080"
    volumes:
      - ./conf-files/as:/root/authentication-service/src/main/resources/private
      - ./properties/as/application.properties:/root/authentication-service/src/main/resources/application.properties
      - ./properties/as/log4j.properties:/root/authentication-service/src/main/resources/log4j.properties